// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElHeader: typeof import('element-plus/es')['ElHeader']
  const ElMain: typeof import('element-plus/es')['ElMain']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  const ElTag: typeof import('element-plus/es')['ElTag']
}
export {}
